name: dongo_chat
description: "The perfect chat to be Dongo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: 0.10.4
  provider: ^6.1.4
  crypto: ^3.0.6
  pointycastle: ^3.6.2
  encrypt: ^5.0.3
  shared_preferences: ^2.5.3
  scrollable_positioned_list: ^0.3.8
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  dio: ^5.8.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  http: ^1.3.0
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^19.1.0
  synchronized: ^3.3.1
  basic_utils: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  assets:
    - assets/ajolote contrast.png
    - assets/animations/
    - news.json
