// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPqwNiL8gpE3VP1nmouMm_7ARxlesZMI',
    appId: '1:860054493117:web:8ec86f2d0edf40319824d4',
    messagingSenderId: '860054493117',
    projectId: 'onara-6d831',
    authDomain: 'onara-6d831.firebaseapp.com',
    storageBucket: 'onara-6d831.appspot.com',
    measurementId: 'G-569Y6XBTMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2a_xO81654y8Aoj1a_BBdiGdkMIB_rWA',
    appId: '1:860054493117:android:7f77aacebf00def49824d4',
    messagingSenderId: '860054493117',
    projectId: 'onara-6d831',
    storageBucket: 'onara-6d831.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjPqwNiL8gpE3VP1nmouMm_7ARxlesZMI',
    appId: '1:860054493117:web:35d3c2960b583fca9824d4',
    messagingSenderId: '860054493117',
    projectId: 'onara-6d831',
    authDomain: 'onara-6d831.firebaseapp.com',
    storageBucket: 'onara-6d831.appspot.com',
    measurementId: 'G-LTNDDFPLTL',
  );
}
