name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: |
      !contains(toJson(github.event.issue.labels), 'cancelled') &&
      !contains(toJson(github.event.issue.labels), 'wontfix')
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/MagincyanGames/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, needs-triage
          label-operator: OR
